# -*- coding: utf-8 -*-
"""Sentiment Analysis on Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnOYD5SYyWQGOrP2wMEFoWegxB6_20hp
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv('IMDB Dataset.csv')

print(df.head())

print(df.info())

print(df.isnull().sum())
df = df.dropna()

print(df["sentiment"].value_counts())

X = df["review"]

y = df["sentiment"]

y = y.map({"positive":1,"negative":0})

vectorizer = TfidfVectorizer(stop_words="english")

X = vectorizer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

review = [input("Enter a review: ")]

review = np.array(review)

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

if prediction[0] == 1:
    print("Positive Review 😊")
else:
    print("Negative Review 😞")